services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/videos:/app/static/videos
      - ./:/app/
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/videos:/app/static/videos
    depends_on:
      - web

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: http --domain=${NGROK_DOMAIN} web:5000
    depends_on:
      - web
